import os, sys
from datetime import datetime

# convert a rom for header purposes
if(len(sys.argv) < 2):
    print(f'usage: {sys.argv[0]} [romfile]')
    sys.exit(1)

with open(sys.argv[1], 'rb') as f:
    b = bytes(f.read())

# do some padding just to be on the safe side
if len(b) < 8192:
    print('Padding to 8k')
    while len(b) < 8192:
        b = b + bytes([0x00])
elif len(b) < 16384:
    print('Padding to 16k')
    while len(b) < 16384:
        b = b + bytes([0x00])
else:
    print(f"Danger: this ROM size ({len(b)}) seems like it's more than 16K, which the cartridge does not currently support")

with open('p6_bootrom.h', 'w') as w:
    w.write('// generated by headerize.py on ' + str(datetime.now()) + '\n')
    w.write('// original command line ' + ' '.join(sys.argv[1:]) + '\n')
    w.write("#ifndef __P6_BOOTROM_H__\n#define __P6_BOOTROM_H__\n\n")
    w.write('unsigned char P6_bootrom[] = {\n')
    count = 0
    for o in range(len(b)):
        w.write('\t' + hex(b[o]) + ',')
        count += 1
        if count % 8 == 0:
            w.write('\n')
    w.write('};\n\n')
    w.write(f'unsigned int P6_bootrom_len = {len(b)}; // does not appear to ever be consumed\n\n')
    w.write("#endif\n")
